name: Deploy Weather App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Pull Latest Code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 194.163.40.83
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/html/weather-app
            git reset --hard
            git pull origin master
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            echo "Deployment berhasil!"
